# Installation directory for clam
CLAM_INSTALL=${HOME}/Repos/clam14/install-release
# Installation directory for llvm
LLVM_HOME=${HOME}/src/llvm-14.0.0.src/install-release
# Installation directory for Boost
BOOST_ROOT=/opt/homebrew
# Installation directory for GMP 
GMP_DIR=/opt/homebrew
# Installation directory for MPFR (needed only by Apron and Elina)
MPFR_DIR=/opt/homebrew

# whether clam was compiled with flag -DCRAB_USE_ELINA=ON or
# -DCRAB_USE_APRON=ON
ELINA_OR_APRON ?= APRON

## Include this file if Clam was built without external libraries
## (ldd, apron, elina)
include Makefile.config

## Include this file if Clam was built with external libraries (ldd,
## apron, elina).
#include Makefile.external.config


