# Installation directory for clam
CLAM_INSTALL=${HOME}/Repos/clam-dev10/install-release
# Installation directory for llvm
LLVM_HOME=${HOME}/src/llvm-10.0.1.src/install-release
# Installation directory for Boost
BOOST_ROOT=/opt/homebrew
# Installation directory for GMP 
GMP_DIR=/opt/homebrew
# Installation directory for MPFR (needed only by Apron and Elina)
MPFR_DIR=/opt/homebrew

include Makefile.config
#include Makefile.external.config

